[build]
command = "npm run build"  # Your build command
publish = "build"          # Directory to publish
# Redirect example
[[redirects]]
from = "/*"
to = "/login.ejs"
status = 200
force = true

# Environment variables
[build.environment]
MONGO_URI_Cloud = "mongodb+srv://ethiodove0:2cHhxhB6HEEqx6rD@cluster0.d4nes5x.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
